vcfa:
  url: "https:/<vcfa-host>"
  auth:
    provider:
      org_name: "system"
      username: "administrator"
      password: "VMware"
      api_version: "40.0"
      storageClass: "Development"
      updateRegionStorageClass: "VM Encryption Policy"
      regionId: "urn:vcloud:region:xxxxx"
    tenant:
      org_name: "coke"
      access_token: "null"
      username: "admin"
      password: "VMware"
  ssl:
    verify_ssl: true
    truststore:
      alias: "TenantManagerCert"
      type: "JKS"