vcfa:
  url: "https://<vcfa-host>"
  auth:
    provider:
      org_name: "system"
      username: "administrator"
      password: "VMware"
      api_version: "40.0"
    tenant:
      org_name: "coke"
      access_token: "null"
      username: "admin"
      password: "VMware"
  ssl:
    verify_ssl: true
    trust_store:
      alias: "TenantManagerCert"
      type: "JKS"