vcfa:
  url: "https://vcfa.172.20.53.59.vcfd.broadcom.net"
  auth:
    provider:
      org_name: "system"
      username: "admin"
      password: "IX7jefeBUK@PpkXTjXsi"
      api_version: "40.0"
      storageClass: "Development"
    tenant:
      org_name: "coke"
      access_token: "null"
      username: "admin"
      password: "VMware"
  ssl:
    verify_ssl: true
    truststore:
      alias: "TenantManagerCert"
      type: "JKS"